### ISSUE TITLE
 Some urls are broken.

### ISSUE THREAD

**Issue by jinwooklim** [MoonBlvd/Detection-of-Traffic-Anomaly#1]
Hello !

I came to inform you that urls are broken.

1. https://www.youtube.com/watch?v=zRZ9PJguIfE # Network is unreachable (I tried it on some computers, but I don't know why network is unreachable.)
2. https://www.youtube.com/watch?v=xToi8YVZM8o # violating
3. https://www.youtube.com/watch?v=6E2N9ld0eHg # violating

**Comment by MoonBlvd** [comment]
Hi @jinwooklim , thank you for letting us know! It's unfortunate that they have made these videos unavailable. The first link you posted works fine, maybe you should check your network setting or so.  I have added the latter two videos into the google drive link in the README file. Please feel free to close this issue if your question is addressed properly. Thanks!

**Comment by jinwooklim** [comment]
All problems are solved. Thank you !
