### ISSUE TITLE
Please update cookies file

### ISSUE THREAD

**Issue by GuitarZH** [MoonBlvd/Detection-of-Traffic-Anomaly#13]
Hi,
Cookies file that was released in Aug can not be downloaded now.  
The outdated link is _https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg_

Can you release a new cookies file?
Thanks a lot for your help!

**Comment by MoonBlvd** [comment]
Hi @GuitarZH, according to my understanding, cookie file should be for each person to download age restricted videos. Please follow [this](https://github.com/blackjack4494/yt-dlc/issues/7) to generate your own cookie file. Thank you!

**Comment by GuitarZH** [comment]
I truly appreciate your timely help！I will try this to download all videos that are mentioned in DoTA dataset.  Thanks for describing the method of generating cookie file in readme.md.

**Comment by MoonBlvd** [comment]
Great, thanks!
