### ISSUE TITLE
Error while executing video download script due to youtube video being private.

### ISSUE THREAD

**Issue by ishamandrekar** [MoonBlvd/Detection-of-Traffic-Anomaly#14]
Hi,
I am trying to download the videos using the script, I am getting error at [youtube] kN-2mc561GY: Downloading webpage ERROR: kN-2mc561GY: YouTube said: Unable to extract video data Traceback (most recent call last): File "C:\Users\Isha\Anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info ie_result = ie.extract(url) File "C:\Users\Isha\Anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract ie_result = self._real_extract(url) File "C:\Users\Isha\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1848, in _real_extract 'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id) youtube_dl.utils.ExtractorError: kN-2mc561GY: YouTube said: Unable to extract video data

Can you please add this one too to the google drive videos provided. Thanks.

**Comment by MoonBlvd** [comment]
Sorry for the late response, please refer to #18

**Comment by MoonBlvd** [comment]
Please see the updated readme for data downloading link. Sorry for the delay and thank you for your patience!
