### ISSUE TITLE
Additional Broken URLs

### ISSUE THREAD

**Issue by jhhan45** [MoonBlvd/Detection-of-Traffic-Anomaly#18]
First of all, thanks for the good dataset to detect traffic anomalies. 
There are several additional broken URLs as follows. 
Would you please upload these raw videos through google drive?

﻿https://www.youtube.com/watch?v=kN-2mc561GY
https://www.youtube.com/watch?v=krPRThe7R4g
https://www.youtube.com/watch?v=JV0D-YkWHD8
https://www.youtube.com/watch?v=CyeT8rEQOpQ
https://www.youtube.com/watch?v=ezY7QrSWeWw
https://www.youtube.com/watch?v=GdyJqgxlSxs
https://www.youtube.com/watch?v=K1r3m5OrmB4
https://www.youtube.com/watch?v=gDjeTHGWX9c
https://www.youtube.com/watch?v=IFhWIS-Gwps
https://www.youtube.com/watch?v=HeK6zbf8I9Y
https://www.youtube.com/watch?v=6I7Dz0qF4NA
https://www.youtube.com/watch?v=RASKiMoxhOE
https://www.youtube.com/watch?v=pQdl0apLT70
https://www.youtube.com/watch?v=e3hXj7S3QyA
https://www.youtube.com/watch?v=GJr8wKk8-YA
https://www.youtube.com/watch?v=Jt6_hinpKpk
https://www.youtube.com/watch?v=GDejMONyY4U
https://www.youtube.com/watch?v=eW9vWga9F5M
https://www.youtube.com/watch?v=Hfs4AlBmg70
https://www.youtube.com/watch?v=Z9K13eBUwJM
https://www.youtube.com/watch?v=ecRog9N1Qf0
https://www.youtube.com/watch?v=DkjTJcCXipY
https://www.youtube.com/watch?v=uO2zGO5ydBc
https://www.youtube.com/watch?v=1u69z-wsDIc
https://www.youtube.com/watch?v=WWyeuvpHmfc
https://www.youtube.com/watch?v=i0Ya-cy2WgY
https://www.youtube.com/watch?v=hy433gakFeo
https://www.youtube.com/watch?v=KOm5jw8vGrE
https://www.youtube.com/watch?v=EJ4VM9wLNXQ
https://www.youtube.com/watch?v=GR4c34BIcVw
https://www.youtube.com/watch?v=GRDP68ucrBM
https://www.youtube.com/watch?v=GYWPqbrY8Z4
https://www.youtube.com/watch?v=kld-iYpdjyo
https://www.youtube.com/watch?v=xVfPBzDnI2Q

**Comment by MoonBlvd** [comment]
Please see the updated readme for data downloading link. Sorry for the delay and thank you for your patience!
