### ISSUE TITLE
json file has wrong format

### ISSUE THREAD

**Issue by jinwooklim** [MoonBlvd/Detection-of-Traffic-Anomaly#2]
Hello !

In 'bFGmOp9H3MA_001987.json', 'accident_id' corresponding to 'frame_id' 41 to 89 is changed to 'accident_name'.

Unfortunately, I haven't checked for other files yet.

**Comment by MoonBlvd** [comment]
@jinwooklim Thank you for letting us know! I have updated the `DoTA_annotations.zip` file.
