### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by hujichn** [MoonBlvd/Detection-of-Traffic-Anomaly#21]
Hi, 
Is it possible to split the dataset file into 5-6 smaller parts？
I met the following error when downloading files from Google Drive:
Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by hujichn** [comment]
Downloaded successfully.

**Comment by desenzhou** [comment]
@hujichn Hi, I met the problem that the 55G file is too large. I tried to download the file many many times and it always failed after downloading about 15G.. How did you successfully resolve this problem?
