### ISSUE TITLE
when can I release your code

### ISSUE THREAD

**Issue by HK017** [MoonBlvd/Detection-of-Traffic-Anomaly#3]
Hello, when can I release your code

**Comment by MoonBlvd** [comment]
Hi @HK017 I'm guessing your question is when will *us release our code? We plan to release our code after our paper is accepted.

**Comment by HK017** [comment]
thank you for you reply, look forward to receiving your paper!

**Comment by MoonBlvd** [comment]
Hi @apbraga , I have added an example dataloader that we used for training the models. I also added the link to download the extracted data for FOL training and testing in the readme file.

**Comment by apbraga** [comment]
Thank you very much @MoonBlvd , appreciate your help! I will start working with that.
From my side this issue is closed, @HK017 could you check if the provided code is inline with your expectation, and if yes, please close the issue.

**Comment by MoonBlvd** [comment]
@apbraga  You are welcome! Please note that the anomaly start and end annotations are only used for evaluation in our paper so we do not have a specific dataloader for that. The way we evaluate VAD is to generate binary-value label vector based on the annotated anomaly start and end.
