### ISSUE TITLE
Youtube download fails for age restricted videos

### ISSUE THREAD

**Issue by apbraga** [MoonBlvd/Detection-of-Traffic-Anomaly#6]
Age restricted videos download fails with current code.

It is necessary to add cookies argument to ydl_opt:

```
ydl_opt = {'cookiefile': 'PATH_TO_COOKIES/cookies.txt', 
                  'outtmpl':os.path.join(DOWNLOAD_DIR, '%(id)s.%(ext)s'),
                  'format': 'mp4'}
```

To get cookies file one can use cookies.txt extension in chrome
https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

The following list of links are the ones that fails without cookies.
https://www.youtube.com/watch?v=DpQBo4gb6Lw
https://www.youtube.com/watch?v=xVfPBzDnI2Q
https://www.youtube.com/watch?v=UKBuDqU8qTM
https://www.youtube.com/watch?v=kld-iYpdjyo
https://www.youtube.com/watch?v=WWyeuvpHmfc
https://www.youtube.com/watch?v=yB6fjM1UUC0
https://www.youtube.com/watch?v=uO2zGO5ydBc
https://www.youtube.com/watch?v=DkjTJcCXipY
https://www.youtube.com/watch?v=ecRog9N1Qf0
https://www.youtube.com/watch?v=qYonJ4w6SZs
https://www.youtube.com/watch?v=Z9K13eBUwJM
https://www.youtube.com/watch?v=Hfs4AlBmg70
https://www.youtube.com/watch?v=88LcRU7uEFE
https://www.youtube.com/watch?v=GDejMONyY4U
https://www.youtube.com/watch?v=Jt6_hinpKpk
https://www.youtube.com/watch?v=oZaUkhs_H-s
https://www.youtube.com/watch?v=GJr8wKk8-YA
https://www.youtube.com/watch?v=e3hXj7S3QyA
https://www.youtube.com/watch?v=pQdl0apLT70
https://www.youtube.com/watch?v=5vKPYV5w6pw
https://www.youtube.com/watch?v=Eq7_uD2yN5Y
https://www.youtube.com/watch?v=RASKiMoxhOE
https://www.youtube.com/watch?v=d2SCftR5sWc
https://www.youtube.com/watch?v=bhA2ckvE-TQ
https://www.youtube.com/watch?v=kN-2mc561GY
https://www.youtube.com/watch?v=QeuzUfHIWYU
https://www.youtube.com/watch?v=krPRThe7R4g
https://www.youtube.com/watch?v=JV0D-YkWHD8
https://www.youtube.com/watch?v=CyeT8rEQOpQ
https://www.youtube.com/watch?v=fdvMUP8qvzw
https://www.youtube.com/watch?v=ezY7QrSWeWw
https://www.youtube.com/watch?v=DyzL2sahobA
https://www.youtube.com/watch?v=GdyJqgxlSxs
https://www.youtube.com/watch?v=K1r3m5OrmB4
https://www.youtube.com/watch?v=gDjeTHGWX9c
https://www.youtube.com/watch?v=IFhWIS-Gwps
https://www.youtube.com/watch?v=HeK6zbf8I9Y
https://www.youtube.com/watch?v=zRZ9PJguIfE

**Comment by MoonBlvd** [comment]
Hi @apbraga . Thank you for your contribution! I have merged your commit.

**Comment by apbraga** [comment]
Happy to help! Great work putting the dataset together. 👍👍
