### ISSUE TITLE
Dataloader example Launcher

### ISSUE THREAD

**Issue by apbraga** [MoonBlvd/Detection-of-Traffic-Anomaly#8]
In the readme file, under the "Extracted data for FOL model training and testing" section, I believe there is a typo.

--log_config >> --load_config

From
`python dataloader_example.py --log_config config/config_example.yaml`

To
`python dataloader_example.py --load_config config/config_example.yaml`

**Comment by MoonBlvd** [comment]
@apbraga You are right, I just fixed it. Sorry about that!

**Comment by apbraga** [comment]
Great! Thanks for the quick reply.
