### ISSUE TITLE
Another broken url

### ISSUE THREAD

**Issue by mcximing** [MoonBlvd/Detection-of-Traffic-Anomaly#9]
Hi, thanks for your excellent work! I downloaded your dataset yesterday and found that this video is not available:
[https://www.youtube.com/watch?v=1u69z-wsDIc](https://www.youtube.com/watch?v=1u69z-wsDIc)
Just FYI.

**Comment by MoonBlvd** [comment]
Hi @mcximing , thank you for letting us know. We will try to add this video to our provided google drive folder and will let you know once done.

**Comment by vnlebaoduy** [comment]
@MoonBlvd Can u add this video again ?. Thanks so much

**Comment by MoonBlvd** [comment]
Hi @mcximing  and @vnlebaoduy , thank you for being patient. I have added this video to the google drive folder. Please close this issue if you have no further concerns. Thank you!

**Comment by ishamandrekar** [comment]
Hi,
  I am trying to download the videos using the script, I am getting error at [youtube] kN-2mc561GY: Downloading webpage                                                                              ERROR: kN-2mc561GY: YouTube said: Unable to extract video data                                                          Traceback (most recent call last):                                                                                        File "C:\Users\Isha\Anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info                       ie_result = ie.extract(url)                                                                                           File "C:\Users\Isha\Anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 532, in extract                     ie_result = self._real_extract(url)                                                                                   File "C:\Users\Isha\Anaconda3\lib\site-packages\youtube_dl\extractor\youtube.py", line 1848, in _real_extract             'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)                                         youtube_dl.utils.ExtractorError: kN-2mc561GY: YouTube said: Unable to extract video data 

Can you please add this one too. Thanks.

**Comment by Taoismer** [comment]
@mcximing Hi， so many video were broken. Can you share your video downloaded before?

**Comment by MoonBlvd** [comment]
Please refer to #18
